# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pick_Up', models.CharField(default=b'', max_length=200)),
                ('Drop_Off', models.CharField(default=b'', max_length=200)),
                ('Pick_Up_Date', models.CharField(default=b'', max_length=200)),
                ('Drop_Off_Date', models.CharField(default=b'', max_length=200)),
                ('First_Name', models.CharField(default=b'', max_length=200)),
                ('Last_Name', models.CharField(default=b'', max_length=200)),
                ('Telephone_Number', models.CharField(blank=True, max_length=20)),
                ('Age', models.CharField(blank=True, max_length=20)),
                ('Email_Address', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(default=b'', max_length=200)),
                ('State', models.CharField(default=b'', max_length=200)),
                ('Country', models.CharField(default=b'', max_length=200)),
                ('Licence_Number', models.CharField(default=b'', max_length=200)),
                ('Expiration_Date', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Available', models.BooleanField(default=True)),
                ('CustomerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CustomerOrder')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Aircondition', models.CharField(max_length=200)),
                ('CostPerDay', models.IntegerField(default=0)),
                ('logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='rented',
            name='VehicleOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.VehicleOrder'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.VehicleOrder'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
