# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='logo',
            field=models.CharField(max_length=200),
        ),
    ]
