# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160810_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='logo',
            field=models.FileField(max_length=200, upload_to=b''),
        ),
    ]
