# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160810_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleorder',
            name='Transmission',
            field=models.CharField(default=b'Automatic', max_length=200),
        ),
    ]
